### ISSUE TITLE
Minimum requirements for node

### ISSUE THREAD

**Issue by spingee** [SAFE-Stack/SAFE-Stack.github.io#16]
Hi,
I tried your new SAFE.Template and had nodejs 8.1.3 installed - web pack failed to start and upgrading nodejs fixed the issue.
Problem is you have version 8+ in quick start as minimum requirement.
Regards

**Comment by martinbryant** [comment]
As of now the quick start documentation mentions node 16 as a minimum requirement

**Comment by mattgallagher92** [comment]
Thanks for raising this issue @spingee and sorry for taking so long! We've put some better processes in place to keep on top of them in future :+1:
