### ISSUE TITLE
Link to Fable.MaterialUI is outdated.

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-Stack.github.io#20]
The link is broken and the  project hasn't been maintained for a long time.

**Comment by martinbryant** [comment]
This is an issue in the docs repo - https://github.com/SAFE-Stack/docs - and as of today the links are all working

**Comment by mattgallagher92** [comment]
Thanks for raising this issue @halcwb and sorry for taking so long to reply! We've put some better processes in place to keep on top of issues in future :+1:
