### ISSUE TITLE
Link to Feliz.Reactstrap is wrong

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-Stack.github.io#21]
Link refers to Feliz.MaterialUI.

**Comment by martinbryant** [comment]
This is an issue with the docs repo - https://github.com/SAFE-Stack/docs - and the link is ok as of today

**Comment by mattgallagher92** [comment]
Thanks for raising this issue @halcwb and sorry for taking so long to reply! We've put some better processes in place to keep on top of issues in future :+1:
