### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by ShalokShalom** [SAFE-Stack/SAFE-Stack.github.io#22]
The current about page links to an article, that advertises Freya. 

Freya is no active in development anymore. 

https://www.compositional-it.com/news-blog/introducing-the-safe-stack/

**Comment by martinbryant** [comment]
Hi @ShalokShalom as the article mentioned is a blog post and it is dated, then I believe readers will be able to see that this may possibly be no longer be relevant today.
