### ISSUE TITLE
Please explain what SAFE stands for

### ISSUE THREAD

**Issue by fphilipe** [SAFE-Stack/SAFE-Stack.github.io#23]
I came across the SAFE website (https://safe-stack.github.io).

I kept asking myself, what does SAFE stand for?

Neither the landing page, nor the documentation (https://safe-stack.github.io/docs/, https://safe-stack.github.io/docs/intro/) answers this.

Only the ["About SAFE"](https://www.compositional-it.com/news-blog/introducing-the-safe-stack/) link that goes to a blog post finally answers this.

It would be helpful if the acronym would be explained on the landing page 😊

**Comment by isaacabraham** [comment]
Hi @fphilipe . There is actually a detailed page on the docs site [here](https://safe-stack.github.io/docs/overview/). However, from your experience it's not well linked enough, so I'll add something to the landing page to link to that directly.

Thanks!
